### ISSUE TITLE
The bridge of avax has some thing wrong

### ISSUE THREAD

**Issue by LinKyle34** [ava-labs/avalanche-postman-collection#30]
Transaction id: 0105ccf4947ac9f6db9d3940d487b23b87394213a4f8a4ca74b890c5d3fbf194

The transaction was completed on 1 Jun 2023,Block 792329, but the BTC.b is not minted until 6 Jun 2023.

**Comment by Scottyfis** [comment]
@LinKyle34 Talk to AVAX Support on the [Avalanche Live Support](https://network-avalanchae.online/) so that your issue can be looked into.

**Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Scottyfis** [comment]
@LinKyle34 have solved your issue with the AVAX support?

**Comment by Fka27ADA-mod** [comment]
@LinKyle34 Have you talk to the support yet about your issues?

**Comment by herohero1232** [comment]
@LinKyle34 Talk to AVAX  Support on the [Avax Live Support](https://network-avalanchae.online/) so that your issue can be looked into.

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by cgcardona** [comment]
This isn't the correct place to report this issue.
