### ISSUE TITLE
Avax

### ISSUE THREAD

**Issue by P-qu** [ava-labs/avalanche-postman-collection#35]
> [!NOTE]
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]
> Crucial information necessary for users to succeed.
@octocat :+1: This PR looks great - it's ready to merge! [`:billetes:`](https://d.docs.live.net/b38e9eefab685324/Documentos/Incluye%20el%20vínculo%20.txt)
> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
/

**Comment by laviniat1996** [comment]
@P-qu Not sure what this is, but doesn't seem relevant.
